# Generated by Django 3.2.9 on 2021-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/%Y/%m/%d/', verbose_name='profile_pic'),
        ),
    ]
