# Generated by Django 3.2.9 on 2021-11-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msAuthApp', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
