# Generated by Django 3.2.9 on 2021-11-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msAuthApp', '0004_alter_user_profile_pic'),
        ('msAuthApp', '0004_auto_20211122_1207'),
    ]

    operations = [
    ]
